### ISSUE TITLE
[feature request]UDP支持，UI界面的bypass客户端管理

### ISSUE THREAD

**Issue by QiuSimons** [vernesong/OpenClash#15]
![image](https://user-images.githubusercontent.com/45143996/63586065-17d33600-c5d3-11e9-9ebe-d4bf57138dd6.png)
您好开发者，请问这两项功能有增加的计划么？
UDP转发可以解决一部分游戏玩家的需求。

至于客户端ip管理，目前可以通过在自定义规则里加规则来解决bypass或者go through的需求，但是能不能考虑增加一个gui的选单，这样会不会优雅一点？

总之还是很感谢开发者的付出的，很勤勉的开发者，修复了许多日常使用发现的bug

**Comment by vernesong** [comment]
1. 这个图片没有说清楚，UDP目前只转发DNS的原因是因为内核的tun还没开发出来，所以像游戏这种的udp流量是代理不了的，请等待内核开发进度，我不太想把插件做太脓肿了。

2. 前提：必须使用dnsmasq，不影响其他插件的正常工作。
用iptables实现访问控制我考虑过，但由于Fake-IP的特殊性和clash自带DNS服务的原因，做不到这个功能在Fake和Redir下的通用性，除非找到能用Dnsmasq指定局域网某些设备dns服务器的方法（目前没找到），所以放弃。

**Comment by QiuSimons** [comment]
> 1. 这个图片没有说清楚，UDP目前只转发DNS的原因是因为内核的tun还没开发出来，所以像游戏这种的udp流量是代理不了的，请等待内核开发进度，我不太想把插件做太脓肿了。
> 2. 前提：必须使用dnsmasq，不影响其他插件的正常工作。
>    用iptables实现访问控制我考虑过，但由于Fake-IP的特殊性和clash自带DNS服务的原因，做不到这个功能在Fake和Redir下的通用性，除非找到能用Dnsmasq指定局域网某些设备dns服务器的方法（目前没找到），所以放弃。

谢谢您的回复，感谢您开发的openclash

**Comment by kmahyyg** [comment]
At the time of this reply(Jan 28, 2021), cooperate with dnsmasq, I think we might have some idea for the client bypass under fake-ip mode.

In my opinion,
We need to do three things for achieving this purpose...

1. Let the specific ip address using `-j RETURN` directly without pass the the traffic from this client to clash, maybe another ipset list should be created.
2. According to: https://serverfault.com/questions/509388/per-client-dns-servers-with-dnsmasq, it is possible to send different DNS to different client. Just try to let dnsmasq include another conf file created by openclash, and modify this created file should work.
3. Since DNS resolution is bypassed, we need to have an option to send a backup DNS to that client. Then it could access the internet...

We made both route, DNS, IP Address all bypassed. Now it should work.

Comments welcomed. And Thanks for your excellent work and contributions. @vernesong

**Comment by kmahyyg** [comment]
For UDP support, we've already have clash core in TUN mode. Now it works.
