### ISSUE TITLE
kmod-inet-diag 这个依赖官方源还没有，从哪里获得？

### ISSUE THREAD

**Issue by yanyingjie007** [vernesong/OpenClash#2174]
kmod-inet-diag 这个依赖官方源还没有，从哪里获得？

**Comment by malikshi** [comment]
Yes. I didn't found official kmod-inet-diag

**Comment by adminidor** [comment]
![kmod-inet-diag](https://user-images.githubusercontent.com/1283711/159398071-b777019c-698a-4bd9-987b-c18cac2f4055.png)

**Comment by vernesong** [comment]
master是有的，其他分支可能没同步

**Comment by malikshi** [comment]
Ok. I will try compile later

**Comment by takenusername** [comment]
直接安装 ipk 可以么？
ipq60xx，aarch64_cortex-a53+crypto，qsdk 应该用哪一个，[a53 packages](https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/packages/) 里面没有，看[其他分支](https://downloads.openwrt.org/snapshots/targets/ipq806x/generic/packages/)都有了。

**Comment by lifetyper** [comment]
openclash搭配lean或者immortalwrt的代码编译比较舒服

**Comment by mmeiwenlong** [comment]
> ![kmod-inet-diag](https://user-images.githubusercontent.com/1283711/159398071-b777019c-698a-4bd9-987b-c18cac2f4055.png)

怎么单独安装这个diag

**Comment by malikshi** [comment]
> > ![kmod-inet-diag](https://user-images.githubusercontent.com/1283711/159398071-b777019c-698a-4bd9-987b-c18cac2f4055.png)
> 
> 怎么单独安装这个diag

Can someone create simple wiki/tutorial for that since it's only available on master.

**Comment by mmeiwenlong** [comment]
> > > ![kmod-inet-diag](https://user-images.githubusercontent.com/1283711/159398071-b777019c-698a-4bd9-987b-c18cac2f4055.png)
> > 
> > 怎么单独安装这个diag
> 
> Can someone create simple wiki/tutorial for that since it's only available on master. 

嗯，我单独编译了一个这个，但又不想升级openwrt，只想升级下openclash

**Comment by vernesong** [comment]
不想要这个可以自己删除makefile里面的内容，编译插件即可

**Comment by malikshi** [comment]
> If you don't want this, you can delete the contents of the makefile yourself and compile the plugin.

i used other openwrt-rpi4 community build and already has kmod-inet-diag since i requested to support it.

it's hard for general users to compile kmod-inet-diag.

**Comment by silmee** [comment]
我也想知道，不重新编译的情况下 哪里有 kmod-inet-diag

**Comment by srduino** [comment]
这个意思就是不能使用官方的二进制版本了，只能自己编译了才能有这个选项？

**Comment by MBRjun** [comment]
> 我也想知道，不重新编译的情况下 哪里有 kmod-inet-diag

我尝试安装软件包，但是得到了：
```
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Unknown package 'kmod-inet-diag'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.109-1-974809f18940ab659f16306b93f28d72) for kmod-inet-diag
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-inet-diag found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package kmod-inet-diag.
```
我正在运行的 OpenWrt 内核版本是 5.10.91。

**Comment by Xholam** [comment]
今天到 openwrt 官方网站所用的编译系统 https://openwrt.org/docs/guide-developer/toolchain/use-buildsystem 发现是找不到 kmod-inet-diag 这个模组的，难到这个也有山寨货？
[https://ps-01-1307018427.cos.ap-guangzhou.myqcloud.com/%E8%AE%BA%E5%9D%9B/OpenWrt%E6%A8%A1%E7%BB%84.JPG](url)

**Comment by vernesong** [comment]
暂时没同步而已

**Comment by littoy** [comment]
大佬，能不能改成弱依赖

**Comment by WisdomLove** [comment]
It was because kmod-inet-diag was bind to specified kernel version.
这是因为kmod-inet-diag 是绑定到指定kernel 版本的。

Unknown package 'kmod-inet-diag'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.154-1-40a0e3e20cb51a8bfec871f9be329c9e) for kmod-inet-diag
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-inet-diag found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package kmod-inet-diag.
 * opkg_conf_deinit: Couldn't unlink /var/lock/opkg.lock: No such file or directory.

我的kernel 版本虽然是5.10.154，但是是去年的kernel，kernel的子版本后面的字符(5.10.154-1-40a0e3e20cb51a8bfec871f9be329c9e)不一致。

Upgrade your firmware to latest.  such as my xiaomi AC2100, After I upgrade the sysupgrade file below, kmod-inet-diag can be installed.
请把你的firmware升级到最新，比如我的小米AC2100，在我使用了下面链接中的sysupgrade bin 文件，就可以下载安装kmod-inet-diag这个软件包了。
https://downloads.openwrt.org/snapshots/targets/ramips/mt7621/openwrt-ramips-mt7621-xiaomi_mi-router-ac2100-squashfs-sysupgrade.bin
Please find your sys upgrade bin file below:
请在下列链接找到你的路由器的升级bin文件，并执行升级，升级后重新安装luci等依赖包即可。
https://downloads.openwrt.org/snapshots/targets/ramips/

**Comment by FradSer** [comment]
Use this https://github.com/zerolabnet/OpenClash

**Comment by tedaz** [comment]
如果使用官方代码的话，21.x的版本都没有kmod-inet-diag，也没有简单的办法从其他版本弄个kmod-inet-diag的源代码插入到21.x，这导致21.x无法编译新版的openclash，只能整体升级openwrt。

**Comment by vernesong** [comment]
https://cateee.net/lkddb/web-lkddb/INET_DIAG.html

**Comment by Xholam** [comment]
谢谢，收到了发自我的 iPad在 2025年10月22日，16:35，vernesong ***@***.***> 写道：﻿vernesong left a comment (vernesong/OpenClash#2174)
https://cateee.net/lkddb/web-lkddb/INET_DIAG.html
